FROM golang:1.15 as builder
ARG GOPROXY=direct
WORKDIR 项目绝对路径
COPY . .
RUN go get -d -v ./... 
RUN CGO_ENABLED=0 go build -ldflags="-w -s -extldflags -static" ./cmd/nps/nps.go

FROM scratch
COPY --from=builder 项目路径 /
COPY --from=builder 项目绝对路径下的web文件 /web
VOLUME /conf
CMD ["/nps"]
